[account]
access_token = "3783afc760af77eec5b4a53934d5be7d4e3a4f5f274699c9d9ce2d6d78e0a322b136b7a31ce0ec795cd1b"

[bot_settings]
reply_message = true
appeal = ["бот, ", "?", "дебил, "]
info_text = "Привет! Меня зовут дебил2848, но друзья меня зовут пить пиво. Я эксперементальный ВК-бот, за авторством WheatleyHDD, который до этого создал GhostlyBot. В отличии от прошлого бота, было сделано немало работы над ошибками, включая полный пересмотр архитектуры кода.\n\nХочешь узнать, что я могу? Пиши \"?команды\""
answers_base = "standard_answers.bin"
admins = [388726687]